language: python

python:
    - '3.5'

env:
    - VERSION=$TRAVIS_BUILD_NUMBER

sudo: required

services:
    - docker
    - postgresql

install: "./go setup"

before_script:
  - psql -c 'create database kudos;' -U postgres

script:
    - "./go test"
    - "./go build"
    - "./go push"

